name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Clean Repository
      run: |
        git reset --hard
        git clean -fdx
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4  # Correct version
      with:
        branch: gh-pages
        folder: Week-1